### PR TITLE
Add. Support gitlab runner CI

### LINKED ISSUE #12: Add support for gitlab CI runner environment
See https://docs.gitlab.com/ee/ci/variables/#predefined-variables-environment-variables

Currently fails as unknown: https://gitlab.com/daurnimator/lua-http/-/jobs/85046313

### PR DESCRIPTION
**Pull request by moteus**
Close #12

### CODE REVIEW

**Comment by alerque** [comment]
Any movement on this? I'm considering trying to add support for Github Actions (see #17) but am a bit concerned a similar contribution has gone over a year without merge.

**Comment by moteus** [comment]
I have no ability to test it.
I can merge it and make new release, but it will be good if some one can confirm that this is work solution.

**Comment by alerque** [comment]
Okay thanks. I do have the ability to test Gitlab runners, so I might try to do that for this contribution too. I'll probably work on Actions first through since that's my current itch. Thanks for the response.

**Comment by alerque** [comment]
I just tested this and no it is not working in it's current form. I'm not quite sure why though because the environment variables it's looking for are there. Here is output I get from `env` plus at attempt to run this branch:

```
$ env
SHELL=/bin/bash
CI_PROJECT_NAMESPACE=caleb
GITLAB_USER_ID=2
CI_RUNNER_VERSION=12.2.0
CI_SERVER_NAME=GitLab
CI_RUNNER_DESCRIPTION=iguana-liturgical-monkey
GITLAB_USER_EMAIL=caleb@alerque.com
CI_SERVER_REVISION=09f8edb
CI_RUNNER_EXECUTABLE_ARCH=linux/amd64
CI_REGISTRY_USER=gitlab-ci-token
CI_API_V4_URL=https://gitlab.alerque.com/api/v4
CI_REGISTRY_PASSWORD=[MASKED]
CI_JOB_NAME=testcov
GITLAB_USER_LOGIN=caleb
CI_PROJECT_NAME=luacov-coveralls
CI_PIPELINE_SOURCE=push
CI_BUILD_REF_NAME=gitlab_ci
CI_PIPELINE_ID=5845
CI_BUILD_REF_SLUG=gitlab-ci
CI_COMMIT_REF_SLUG=gitlab-ci
CI_SERVER=yes
CI_COMMIT_SHORT_SHA=0fe5660b
CONFIG_FILE=/etc/gitlab-runner/config.toml
FF_CMD_DISABLE_DELAYED_ERROR_LEVEL_EXPANSION=false
PWD=/var/lib/gitlab-runner/builds/adef497d/0/caleb/luacov-coveralls
CI_RUNNER_TAGS=casile, sile, pdftk, sile-git, iguana, lilypond, mustache, mail, nextcloud, usfm2osis, pandoc, texlive
CI_PROJECT_PATH=caleb/luacov-coveralls
LOGNAME=gitlab-runner
CI_SERVER_TLS_CA_FILE=/var/lib/gitlab-runner/builds/adef497d/0/caleb/luacov-coveralls.tmp/CI_SERVER_TLS_CA_FILE
GIT_STRATEGY=fetch
CI_COMMIT_REF_PROTECTED=false
CI_SERVER_VERSION_MINOR=2
CI_COMMIT_SHA=0fe5660b0b6243954f68e2f60950b7aef2135fd6
HOME=/var/lib/gitlab-runner
LANG=en_US.utf8
CI_PROJECT_VISIBILITY=public
CI_CONCURRENT_PROJECT_ID=0
CI_COMMIT_MESSAGE=Show env variables for debug

CI_BUILD_NAME=testcov
CI_PAGES_DOMAIN=pages.alerque.com
CI_SERVER_VERSION=12.2.5
CI_SHARED_ENVIRONMENT=true
INVOCATION_ID=db172a497ef6429982ea0cdcd4096042
CI_PAGES_URL=http://caleb.pages.alerque.com:8282/luacov-coveralls
CI_PIPELINE_IID=3
CI_REPOSITORY_URL=https://gitlab-ci-token:[MASKED]@gitlab.alerque.com/caleb/luacov-coveralls.git
GITLAB_FEATURES=
CI_COMMIT_DESCRIPTION=
CI_JOB_STAGE=test
CI_PIPELINE_URL=https://gitlab.alerque.com/caleb/luacov-coveralls/pipelines/5845
CI_BUILD_REF=0fe5660b0b6243954f68e2f60950b7aef2135fd6
CI_SERVER_VERSION_PATCH=5
COVERALLS_REPO_TOKEN=[MASKED]
CI_COMMIT_TITLE=Show env variables for debug
USER=gitlab-runner
GITLAB_USER_NAME=Caleb Maclennan
CI_PROJECT_DIR=/var/lib/gitlab-runner/builds/adef497d/0/caleb/luacov-coveralls
SHLVL=1
CI_RUNNER_ID=1
GIT_SSL_CAPATH=/etc/ssl/certs/
CI_BUILD_ID=8919
CI_COMMIT_REF_NAME=gitlab_ci
CI_SERVER_HOST=gitlab.alerque.com
CI_JOB_URL=https://gitlab.alerque.com/caleb/luacov-coveralls/-/jobs/8919
CI_JOB_TOKEN=[MASKED]
CI_CONCURRENT_ID=0
CI_BUILD_TOKEN=[MASKED]
CI_RUNNER_REVISION=a987417a
CI_BUILD_BEFORE_SHA=2143ae696a900772499386dff69eb9d1018ee574
CI_PROJECT_PATH_SLUG=caleb-luacov-coveralls
CI_NODE_TOTAL=1
CI_JOB_ID=8919
CI_BUILDS_DIR=/var/lib/gitlab-runner/builds
FF_USE_LEGACY_BUILDS_DIR_FOR_DOCKER=false
JOURNAL_STREAM=9:22965
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
CI_PROJECT_ID=193
CI=true
GITLAB_CI=true
CI_COMMIT_BEFORE_SHA=2143ae696a900772499386dff69eb9d1018ee574
HG=/usr/bin/hg
CI_SERVER_VERSION_MAJOR=12
CI_CONFIG_PATH=.gitlab-ci.yml
CI_BUILD_STAGE=test
CI_PROJECT_URL=https://gitlab.alerque.com/caleb/luacov-coveralls
OLDPWD=/var/lib/gitlab-runner
FF_USE_LEGACY_VOLUMES_MOUNTING_ORDER=false
_=/usr/bin/env
$ lua -lluacov src/luacov/coveralls/utils.lua
$ lua src/bin/luacov-coveralls -i utils -v
CI: 
  name            : <UNKNOWN>
  branch          : <UNKNOWN>
  service_number  : <UNKNOWN>
  pull_request    : <UNKNOWN>
  job_id          : <UNKNOWN>
  commit_id       : <UNKNOWN>
  author_name     : <UNKNOWN>
  author_email    : <UNKNOWN>
  committer_name  : <UNKNOWN>
  committer_email : <UNKNOWN>
  message         : <UNKNOWN>
  token           : <NOT DETECTED>
Repository: 
  type            : git
  path            : /var/lib/gitlab-runner/builds/adef497d/0/caleb/luacov-coveralls
  version         : git version 2.23.0
  id              : 0fe5660b0b6243954f68e2f60950b7aef2135fd6
  author_name     : Caleb Maclennan
  author_email    : caleb@alerque.com
  committer_name  : Caleb Maclennan
  committer_email : caleb@alerque.com
  message         : Show env variables for debug
  current_branch  : HEAD
File 'src/luacov/coveralls/utils.lua'
Lines executed:33.33% of 99

--------------------
service_name         : 
repo_token           : <NOT DETECTED>
service_number       : 
service_job_id       : 
service_pull_request : 
source_files         : 1
  src/luacov/coveralls/utils.lua
git
  head
    id             : 0fe5660b0b6243954f68e2f60950b7aef2135fd6
    author_name    : Caleb Maclennan
    author_email   : caleb@alerque.com
    committer_name : Caleb Maclennan
    committer_email: caleb@alerque.com
    message        : Show env variables for debug
  branch           : HEAD
  remotes
    origin https://gitlab-ci-token:[MASKED]@gitlab.alerque.com/caleb/luacov-coveralls.git 
--------------------
Uploading ...
Upload error: Couldn't find a repository matching this job.
Raw data:	Couldn't find a repository matching this job.
--------------------
Upload error: Couldn't find a repository matching this job.
Raw data:	Couldn't find a repository matching this job.
--------------------
Upload error: Couldn't find a repository matching this job.
Raw data:	Couldn't find a repository matching this job.
--------------------
Uploading done
```

**Comment by moteus** [comment]
`Couldn't find a repository matching this job.` This usially means that Coveralls has no repo. May be it does not support your CI perhups.

**Comment by alerque** [comment]
No, if you inspect the output you'll see luacov-coveralls didn't detect anything about the repo to send to coveralls. That's because the LUA_PATH was finding `luacov.coveralls.CiInfo` from my system (which has the released version) instead of local to the test.

I fixed that and it works now. The relevant part of the output is here:

```
CI: 
  name            : gitlab
  branch          : gitlab_ci
  service_number  : <UNKNOWN>
  pull_request    : <UNKNOWN>
  job_id          : 8920
  commit_id       : e620ba75bc27e426e90188b8f0004faacd42cdc7
  author_name     : <UNKNOWN>
  author_email    : <UNKNOWN>
  committer_name  : <UNKNOWN>
  committer_email : <UNKNOWN>
  message         : Show env variables for debug
  token           : <DETECTED>
```

I'll send a PR with a couple more supported variables. Unfortunately the author/committer variables are [not supported yet](https://gitlab.com/gitlab-org/gitlab/issues/22061).

**Comment by moteus** [comment]
Authior/Commiter should be calculated based on git info
https://github.com/moteus/luacov-coveralls/blob/be9299e330d02dbe2e803ddde5651fd0889aecd9/src/luacov/coveralls/CiRepo.lua#L39

**Comment by moteus** [comment]
I'll merge it tomorrow if there wil no any comments

**Pull request merged**
